provider:
  environment:
    ${name}: ${service}-${stage}-${name}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.environment.${name}}/*"

resources:
  Resources:
    ${name}:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${service}-${stage}-${name}
    CorsConfiguration:
      CorsRules:
        - AllowedHeaders: ["*"]
          AllowedMethods: [GET, PUT]
          AllowedOrigins: ["*"]
          Id: CORSRuleId1
          MaxAge: "3600"
